# Generated by Django 4.2.11 on 2024-03-16 06:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('basic_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.basic_info')),
            ],
        ),
        migrations.AddField(
            model_name='basic_info',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.department'),
        ),
    ]
